project:
  type: default

format:
  hugo-md: default

filters:
  - _extensions/escape-shortcodes/escape-shortcodes.lua
  - _extensions/strip-bootstrap/strip-bootstrap.lua

bibliography: references.bib
reference-section-title: References
